name: barber_shop
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  animated_custom_dropdown: ^3.1.1
  circular_profile_avatar: 2.0.5
  cloud_firestore: ^4.17.5
  firebase_auth: ^4.17.5
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  lottie: ^3.1.2
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  table_calendar: ^3.1.2
  uuid: ^4.4.2
  validators: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
