// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3ZYmBLMrxRfKizbYhFrasmYftyRSTdF0',
    appId: '1:225731774831:web:3764171d0f94075b90409a',
    messagingSenderId: '225731774831',
    projectId: 'barbershop-3258e',
    authDomain: 'barbershop-3258e.firebaseapp.com',
    storageBucket: 'barbershop-3258e.appspot.com',
    measurementId: 'G-YNG7E58J5W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcxUOHB6twHXbg1B6-Rx6tr1FiEqENnkg',
    appId: '1:225731774831:android:2ec27cf9beb4279590409a',
    messagingSenderId: '225731774831',
    projectId: 'barbershop-3258e',
    storageBucket: 'barbershop-3258e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAqxmwD3-KisjpyFFVy6JC8NtjjLB23UU',
    appId: '1:225731774831:ios:1fccfb2bdc0f788390409a',
    messagingSenderId: '225731774831',
    projectId: 'barbershop-3258e',
    storageBucket: 'barbershop-3258e.appspot.com',
    iosBundleId: 'com.example.barberShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAqxmwD3-KisjpyFFVy6JC8NtjjLB23UU',
    appId: '1:225731774831:ios:1fccfb2bdc0f788390409a',
    messagingSenderId: '225731774831',
    projectId: 'barbershop-3258e',
    storageBucket: 'barbershop-3258e.appspot.com',
    iosBundleId: 'com.example.barberShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3ZYmBLMrxRfKizbYhFrasmYftyRSTdF0',
    appId: '1:225731774831:web:e7cbe30b1480772b90409a',
    messagingSenderId: '225731774831',
    projectId: 'barbershop-3258e',
    authDomain: 'barbershop-3258e.firebaseapp.com',
    storageBucket: 'barbershop-3258e.appspot.com',
    measurementId: 'G-CW205K6PES',
  );

}